=== SkylerGodfrey/jamfprotect/json_samples_and_schemas/alerts/schemas/GPScreenshotEvent.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "host": {
      "type": "object",
      "properties": {
        "os": {
          "type": "string"
        },
        "ips": {
          "type": "array",
          "items": [
            {
              "type": "string"
            }
          ]
        },
        "serial": {
          "type": "string"
        },
        "hostname": {
          "type": "string"
        },
        "protectVersion": {
          "type": "string"
        },
        "provisioningUDID": {
          "type": "string"
        }
      },
      "required": [
        "os",
        "ips",
        "serial",
        "hostname",
        "protectVersion",
        "provisioningUDID"
      ]
    },
    "match": {
      "type": "object",
      "properties": {
        "tags": {
          "type": "array",
          "items": {}
        },
        "uuid": {
          "type": "string"
        },
        "event": {
          "type": "object",
          "properties": {
            "path": {
              "type": "string"
            },
            "uuid": {
              "type": "string"
            },
            "timestamp": {
              "type": "number"
            }
          },
          "required": [
            "path",
            "uuid",
            "timestamp"
          ]
        },
        "facts": {
          "type": "array",
          "items": [
            {
              "type": "object",
              "properties": {
                "name": {
                  "type": "string"
                },
                "tags": {
                  "type": "array",
                  "items": {}
                },
                "uuid": {
                  "type": "string"
                },
                "human": {
                  "type": "string"
                },
                "actions": {
                  "type": "array",
                  "items": [
                    {
                      "type": "object",
                      "properties": {
                        "name": {
                          "type": "string"
                        }
                      },
                      "required": [
                        "name"
                      ]
                    }
                  ]
                },
                "context": {
                  "type": "array",
                  "items": {}
                },
                "version": {
                  "type": "integer"
                },
                "severity": {
                  "type": "integer"
                }
              },
              "required": [
                "name",
                "tags",
                "uuid",
                "human",
                "actions",
                "context",
                "version",
                "severity"
              ]
            }
          ]
        },
        "custom": {
          "type": "boolean"
        },
        "actions": {
          "type": "array",
          "items": [
            {
              "type": "object",
              "properties": {
                "name": {
                  "type": "string"
                }
              },
              "required": [
                "name"
              ]
            }
          ]
        },
        "context": {
          "type": "array",
          "items": {}
        },
        "severity": {
          "type": "integer"
        }
      },
      "required": [
        "tags",
        "uuid",
        "event",
        "facts",
        "custom",
        "actions",
        "context",
        "severity"
      ]
    },
    "related": {
      "type": "object",
      "properties": {
        "files": {
          "type": "array",
          "items": [
            {
              "type": "object",
              "properties": {
                "gid": {
                  "type": "integer"
                },
                "uid": {
                  "type": "integer"
                },
                "fsid": {
                  "type": "integer"
                },
                "mode": {
                  "type": "integer"
                },
                "path": {
                  "type": "string"
                },
                "size": {
                  "type": "integer"
                },
                "inode": {
                  "type": "integer"
                },
                "xattrs": {
                  "type": "array",
                  "items": [
                    {
                      "type": "string"
                    },
                    {
                      "type": "string"
                    },
                    {
                      "type": "string"
                    },
                    {
                      "type": "string"
                    },
                    {
                      "type": "string"
                    }
                  ]
                },
                "changed": {
                  "type": "integer"
                },
                "created": {
                  "type": "integer"
                },
                "sha1hex": {
                  "type": "string"
                },
                "accessed": {
                  "type": "integer"
                },
                "modified": {
                  "type": "integer"
                },
                "sha256hex": {
                  "type": "string"
                },
                "isDownload": {
                  "type": "boolean"
                },
                "objectType": {
                  "type": "string"
                },
                "isAppBundle": {
                  "type": "boolean"
                },
                "isDirectory": {
                  "type": "boolean"
                },
                "signingInfo": {
                  "type": "object",
                  "properties": {
                    "appid": {
                      "type": "string"
                    },
                    "status": {
                      "type": "integer"
                    },
                    "teamid": {
                      "type": "string"
                    },
                    "signerType": {
                      "type": "integer"
                    },
                    "authorities": {
                      "type": "array",
                      "items": {}
                    },
                    "entitlements": {
                      "type": "array",
                      "items": {}
                    },
                    "statusMessage": {
                      "type": "string"
                    },
                    "informationStage": {
                      "type": "string"
                    }
                  },
                  "required": [
                    "appid",
                    "status",
                    "teamid",
                    "signerType",
                    "authorities",
                    "entitlements",
                    "statusMessage",
                    "informationStage"
                  ]
                },
                "isScreenShot": {
                  "type": "boolean"
                }
              },
              "required": [
                "gid",
                "uid",
                "fsid",
                "mode",
                "path",
                "size",
                "inode",
                "xattrs",
                "changed",
                "created",
                "sha1hex",
                "accessed",
                "modified",
                "sha256hex",
                "isDownload",
                "objectType",
                "isAppBundle",
                "isDirectory",
                "signingInfo",
                "isScreenShot"
              ]
            }
          ]
        },
        "users": {
          "type": "array",
          "items": [
            {
              "type": "object",
              "properties": {
                "uid": {
                  "type": "integer"
                },
                "name": {
                  "type": "string"
                },
                "uuid": {
                  "type": "string"
                }
              },
              "required": [
                "uid",
                "name",
                "uuid"
              ]
            }
          ]
        },
        "groups": {
          "type": "array",
          "items": [
            {
              "type": "object",
              "properties": {
                "gid": {
                  "type": "integer"
                },
                "name": {
                  "type": "string"
                },
                "uuid": {
                  "type": "string"
                }
              },
              "required": [
                "gid",
                "name",
                "uuid"
              ]
            }
          ]
        },
        "binaries": {
          "type": "array",
          "items": {}
        },
        "processes": {
          "type": "array",
          "items": {}
        }
      },
      "required": [
        "files",
        "users",
        "groups",
        "binaries",
        "processes"
      ]
    },
    "eventType": {
      "type": "string"
    }
  },
  "required": [
    "host",
    "match",
    "related",
    "eventType"
  ]
}

=== SkylerGodfrey/jamfprotect/json_samples_and_schemas/alerts/samples/GPDownloadEvent.json
{
  "host": {
    "os": "Version 14.0 (Build 23A344)",
    "ips": [
      "192.168.11.226"
    ],
    "serial": "Z2C23RW4DY",
    "hostname": "VMAC-2C23RW4DY",
    "protectVersion": "5.0.0.1",
    "provisioningUDID": "0000FE00-8406CE28ECFC4DAB"
  },
  "match": {
    "tags": [],
    "uuid": "a17bc30c-a631-4b76-9223-765fb0daa9f8",
    "event": {
      "path": "/Users/local-admin/Downloads/JamfConnect-2.27.0.dmg",
      "uuid": "82b5d972-23b1-46bb-ba58-0ca46db1edbb",
      "timestamp": 1695830406.620384
    },
    "facts": [
      {
        "name": "new_downloads",
        "tags": [],
        "uuid": "e5faa7fe-a10b-461c-9bc3-b3080bb59f4a",
        "human": "",
        "actions": [
          {
            "name": "Report",
            "parameters": {}
          }
        ],
        "context": [],
        "version": 0,
        "severity": 0
      }
    ],
    "custom": true,
    "actions": [
      {
        "name": "Report",
        "parameters": {}
      }
    ],
    "context": [],
    "severity": 0
  },
  "related": {
    "files": [
      {
        "gid": 20,
        "uid": 501,
        "fsid": 16777234,
        "mode": 33188,
        "path": "/Users/local-admin/Downloads/JamfConnect-2.27.0.dmg",
        "size": 35249769,
        "inode": 3779418,
        "xattrs": [
          "com.apple.macl",
          "com.apple.metadata:kMDItemDownloadedDate",
          "com.apple.metadata:kMDItemWhereFroms",
          "com.apple.quarantine"
        ],
        "changed": 1695830406,
        "created": 1695830401,
        "sha1hex": "0a5f0aa7cbe904e687341e2eee453348e3a3760d",
        "accessed": 1695830404,
        "modified": 1695830404,
        "sha256hex": "f7688a83f2c508c16128bd512e1d57b122824001a0c560b12b63c26d3cb7f4a0",
        "isDownload": true,
        "objectType": "GPSystemObject",
        "isAppBundle": false,
        "isDirectory": false,
        "signingInfo": {
          "appid": "JamfConnect-2",
          "cdhash": "sqTVmnuWCrCwmriUwwrilesPYME=",
          "status": 0,
          "teamid": "483DWKW443",
          "signerType": 2,
          "authorities": [
            "Developer ID Application: JAMF Software (483DWKW443)",
            "Developer ID Certification Authority",
            "Apple Root CA"
          ],
          "entitlements": [],
          "statusMessage": "No error."
        },
        "isScreenShot": false,
        "downloadedFrom": [
          "https://files.jamfconnect.com/JamfConnect.dmg"
        ]
      }
    ],
    "users": [
      {
        "uid": 501,
        "name": "local-admin",
        "uuid": "Z2C23RW4DY1f5"
      }
    ],
    "groups": [
      {
        "gid": 20,
        "name": "staff",
        "uuid": "Z2C23RW4DY14"
      }
    ],
    "binaries": [],
    "processes": []
  },
  "eventType": "GPDownloadEvent"
}

=== SkylerGodfrey/jamfprotect/json_samples_and_schemas/alerts/samples/GPScreenshotEvent.json
{
  "host": {
    "os": "Version 14.0 (Build 23A344)",
    "ips": [
      "192.168.11.226"
    ],
    "serial": "Z2C23RW4DY",
    "hostname": "VMAC-2C23RW4DY",
    "protectVersion": "5.1.0.4",
    "provisioningUDID": "0000FE00-8406CE28ECFC4DAB"
  },
  "match": {
    "tags": [],
    "uuid": "e4397538-1042-4c66-b336-08da9e870d87",
    "event": {
      "path": "/Users/local-admin/Desktop/Screenshot 2023-10-23 at 14.58.58.png",
      "uuid": "d4805afb-7158-4043-a93b-bacefb2adca0",
      "timestamp": 1698065945.595533
    },
    "facts": [
      {
        "name": "Screenshot taken",
        "tags": [],
        "uuid": "28db9092-15af-4b65-9bfe-b0eba82e4fdf",
        "human": "",
        "actions": [
          {
            "name": "Report"
          }
        ],
        "context": [],
        "version": 0,
        "severity": 0
      }
    ],
    "custom": true,
    "actions": [
      {
        "name": "Report"
      }
    ],
    "context": [],
    "severity": 0
  },
  "related": {
    "files": [
      {
        "gid": 20,
        "uid": 501,
        "fsid": 16777231,
        "mode": 33188,
        "path": "/Users/local-admin/Desktop/Screenshot 2023-10-23 at 14.58.58.png",
        "size": 0,
        "inode": 4598335,
        "xattrs": [
          "com.apple.FinderInfo",
          "com.apple.macl",
          "com.apple.metadata:kMDItemIsScreenCapture",
          "com.apple.metadata:kMDItemScreenCaptureGlobalRect",
          "com.apple.metadata:kMDItemScreenCaptureType"
        ],
        "changed": 1698065944,
        "created": 1698065944,
        "sha1hex": "b7926e3c44ec93c93a3e71c5b1185865212d498f",
        "accessed": 1698065944,
        "modified": 1698065944,
        "sha256hex": "f49fb0ab0fc6b26ae1c81744e4489e612e9ba6299b4de989e44c585d6de7765a",
        "isDownload": false,
        "objectType": "GPSystemObject",
        "isAppBundle": false,
        "isDirectory": false,
        "signingInfo": {
          "appid": "",
          "status": -67062,
          "teamid": "",
          "signerType": 4,
          "authorities": [],
          "entitlements": [],
          "statusMessage": "code object is not signed at all",
          "informationStage": "extended"
        },
        "isScreenShot": true
      }
    ],
    "users": [
      {
        "uid": 501,
        "name": "local-admin",
        "uuid": "Z2C23RW4DY1f5"
      }
    ],
    "groups": [
      {
        "gid": 20,
        "name": "staff",
        "uuid": "Z2C23RW4DY14"
      }
    ],
    "binaries": [],
    "processes": []
  },
  "eventType": "GPScreenshotEvent"
}
