=== SkylerGodfrey/jamfprotect/json_samples_and_schemas/alerts/schemas/GPThreatMatchExecEvent.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "host": {
      "type": "object",
      "properties": {
        "os": {
          "type": "string"
        },
        "ips": {
          "type": "array",
          "items": [
            {
              "type": "string"
            }
          ]
        },
        "serial": {
          "type": "string"
        },
        "hostname": {
          "type": "string"
        },
        "protectVersion": {
          "type": "string"
        },
        "provisioningUDID": {
          "type": "string"
        }
      },
      "required": [
        "ips",
        "serial",
        "hostname",
        "provisioningUDID"
      ]
    },
    "match": {
      "type": "object",
      "properties": {
        "tags": {
          "type": "array",
          "items": {}
        },
        "uuid": {
          "type": "string"
        },
        "event": {
          "type": "object",
          "properties": {
            "uuid": {
              "type": "string"
            },
            "blocked": {
              "type": "boolean"
            },
            "process": {
              "type": "object",
              "properties": {
                "gid": {
                  "type": "integer"
                },
                "pid": {
                  "type": "integer"
                },
                "uid": {
                  "type": "integer"
                },
                "args": {
                  "type": "array",
                  "items": [
                    {
                      "type": "string"
                    },
                    {
                      "type": "string"
                    }
                  ]
                },
                "name": {
                  "type": "string"
                },
                "path": {
                  "type": "string"
                },
                "pgid": {
                  "type": "integer"
                },
                "ppid": {
                  "type": "integer"
                },
                "rgid": {
                  "type": "integer"
                },
                "ruid": {
                  "type": "integer"
                },
                "uuid": {
                  "type": "string"
                },
                "signingInfo": {
                  "type": "object",
                  "properties": {
                    "appid": {
                      "type": "string"
                    },
                    "status": {
                      "type": "integer"
                    },
                    "teamid": {
                      "type": "string"
                    },
                    "signerType": {
                      "type": "integer"
                    },
                    "authorities": {
                      "type": "array",
                      "items": {}
                    },
                    "entitlements": {
                      "type": "array",
                      "items": {}
                    },
                    "statusMessage": {
                      "type": "string"
                    }
                  },
                  "required": [
                    "appid",
                    "status",
                    "teamid",
                    "signerType",
                    "authorities",
                    "entitlements",
                    "statusMessage"
                  ]
                },
                "startTimestamp": {
                  "type": "integer"
                },
                "originalParentPID": {
                  "type": "integer"
                }
              },
              "required": [
                "gid",
                "pid",
                "uid",
                "args",
                "name",
                "path",
                "pgid",
                "ppid",
                "rgid",
                "ruid",
                "uuid",
                "signingInfo",
                "startTimestamp",
                "originalParentPID"
              ]
            },
            "matchType": {
              "type": "string"
            },
            "timestamp": {
              "type": "number"
            },
            "matchValue": {
              "type": "string"
            }
          },
          "required": [
            "uuid",
            "blocked",
            "process",
            "matchType",
            "timestamp",
            "matchValue"
          ]
        },
        "facts": {
          "type": "array",
          "items": [
            {
              "type": "object",
              "properties": {
                "name": {
                  "type": "string"
                },
                "tags": {
                  "type": "array",
                  "items": [
                    {
                      "type": "string"
                    }
                  ]
                },
                "uuid": {
                  "type": "string"
                },
                "human": {
                  "type": "string"
                },
                "actions": {
                  "type": "array",
                  "items": [
                    {
                      "type": "object",
                      "properties": {
                        "name": {
                          "type": "string"
                        },
                        "parameters": {
                          "type": "object",
                          "properties": {
                            "title": {
                              "type": "string"
                            },
                            "message": {
                              "type": "string"
                            }
                          },
                          "required": [
                            "title",
                            "message"
                          ]
                        }
                      },
                      "required": [
                        "name",
                        "parameters"
                      ]
                    },
                    {
                      "type": "object",
                      "properties": {
                        "name": {
                          "type": "string"
                        },
                        "parameters": {
                          "type": "object"
                        }
                      },
                      "required": [
                        "name",
                        "parameters"
                      ]
                    },
                    {
                      "type": "object",
                      "properties": {
                        "name": {
                          "type": "string"
                        },
                        "parameters": {
                          "type": "object"
                        }
                      },
                      "required": [
                        "name",
                        "parameters"
                      ]
                    }
                  ]
                },
                "context": {
                  "type": "array",
                  "items": {}
                },
                "version": {
                  "type": "integer"
                },
                "severity": {
                  "type": "integer"
                }
              },
              "required": [
                "name",
                "tags",
                "uuid",
                "human",
                "actions",
                "context",
                "version",
                "severity"
              ]
            }
          ]
        },
        "custom": {
          "type": "boolean"
        },
        "actions": {
          "type": "array",
          "items": [
            {
              "type": "object",
              "properties": {
                "name": {
                  "type": "string"
                },
                "parameters": {
                  "type": "object",
                  "properties": {
                    "title": {
                      "type": "string"
                    },
                    "message": {
                      "type": "string"
                    }
                  },
                  "required": [
                    "title",
                    "message"
                  ]
                }
              },
              "required": [
                "name",
                "parameters"
              ]
            },
            {
              "type": "object",
              "properties": {
                "name": {
                  "type": "string"
                },
                "parameters": {
                  "type": "object"
                }
              },
              "required": [
                "name",
                "parameters"
              ]
            },
            {
              "type": "object",
              "properties": {
                "name": {
                  "type": "string"
                },
                "parameters": {
                  "type": "object"
                }
              },
              "required": [
                "name",
                "parameters"
              ]
            }
          ]
        },
        "context": {
          "type": "array",
          "items": {}
        },
        "severity": {
          "type": "integer"
        }
      },
      "required": [
        "tags",
        "uuid",
        "event",
        "facts",
        "custom",
        "actions",
        "context",
        "severity"
      ]
    },
    "related": {
      "type": "object",
      "properties": {
        "files": {
          "type": "array",
          "items": {}
        },
        "users": {
          "type": "array",
          "items": [
            {
              "type": "object",
              "properties": {
                "uid": {
                  "type": "integer"
                },
                "name": {
                  "type": "string"
                },
                "uuid": {
                  "type": "string"
                }
              },
              "required": [
                "uid",
                "name",
                "uuid"
              ]
            }
          ]
        },
        "groups": {
          "type": "array",
          "items": [
            {
              "type": "object",
              "properties": {
                "gid": {
                  "type": "integer"
                },
                "name": {
                  "type": "string"
                },
                "uuid": {
                  "type": "string"
                }
              },
              "required": [
                "gid",
                "name",
                "uuid"
              ]
            }
          ]
        },
        "binaries": {
          "type": "array",
          "items": {}
        },
        "processes": {
          "type": "array",
          "items": [
            {
              "type": "object",
              "properties": {
                "gid": {
                  "type": "integer"
                },
                "pid": {
                  "type": "integer"
                },
                "uid": {
                  "type": "integer"
                },
                "args": {
                  "type": "array",
                  "items": [
                    {
                      "type": "string"
                    },
                    {
                      "type": "string"
                    }
                  ]
                },
                "name": {
                  "type": "string"
                },
                "path": {
                  "type": "string"
                },
                "pgid": {
                  "type": "integer"
                },
                "ppid": {
                  "type": "integer"
                },
                "rgid": {
                  "type": "integer"
                },
                "ruid": {
                  "type": "integer"
                },
                "uuid": {
                  "type": "string"
                },
                "signingInfo": {
                  "type": "object",
                  "properties": {
                    "appid": {
                      "type": "string"
                    },
                    "status": {
                      "type": "integer"
                    },
                    "teamid": {
                      "type": "string"
                    },
                    "signerType": {
                      "type": "integer"
                    },
                    "authorities": {
                      "type": "array",
                      "items": {}
                    },
                    "entitlements": {
                      "type": "array",
                      "items": {}
                    },
                    "statusMessage": {
                      "type": "string"
                    }
                  },
                  "required": [
                    "appid",
                    "status",
                    "teamid",
                    "signerType",
                    "authorities",
                    "entitlements",
                    "statusMessage"
                  ]
                },
                "startTimestamp": {
                  "type": "integer"
                },
                "originalParentPID": {
                  "type": "integer"
                }
              },
              "required": [
                "gid",
                "pid",
                "uid",
                "args",
                "name",
                "path",
                "pgid",
                "ppid",
                "rgid",
                "ruid",
                "uuid",
                "signingInfo",
                "startTimestamp",
                "originalParentPID"
              ]
            }
          ]
        }
      },
      "required": [
        "files",
        "users",
        "groups",
        "binaries",
        "processes"
      ]
    },
    "eventType": {
      "type": "string"
    }
  },
  "required": [
    "host",
    "match",
    "related",
    "eventType"
  ]
}

=== SkylerGodfrey/jamfprotect/json_samples_and_schemas/alerts/samples/GPPreventedExecutionEvent.json
{
  "host": {
    "os": "Version 14.0 (Build 23A344)",
    "ips": [
      "192.168.11.151"
    ],
    "serial": "Z2C23RW4DY",
    "hostname": "VMAC-2C23RW4DY",
    "protectVersion": "5.0.0.1",
    "provisioningUDID": "32EC79C5-26DC-535A-85F7-986F063297E2"
  },
  "match": {
    "tags": [],
    "uuid": "9a5f6efb-bf7d-4606-b36b-d57dda7eccbb",
    "event": {
      "uuid": "240b6f6c-4fcf-4ca4-a0bd-92feb6b1efe9",
      "blocked": true,
      "process": {
        "gid": 20,
        "pid": 40990,
        "uid": 501,
        "args": [
          "/Applications/IBM Notifier.app/Contents/MacOS/IBM Notifier"
        ],
        "name": "IBM Notifier",
        "path": "/Applications/IBM Notifier.app/Contents/MacOS/IBM Notifier",
        "pgid": 40990,
        "ppid": 1,
        "rgid": 20,
        "ruid": 501,
        "uuid": "d073d34c-4282-46bd-b45b-7bb62e7d0f3d",
        "signingInfo": {
          "appid": "com.ibm.cio.notifier",
          "cdhash": "XZClQWlwUsWw1uZnLhCOvyp7R0s=",
          "status": 0,
          "teamid": "PETKK2G752",
          "signerType": 2,
          "authorities": [
            "Developer ID Application: International  Business Machines Corp (PETKK2G752)",
            "Developer ID Certification Authority",
            "Apple Root CA"
          ],
          "entitlements": [],
          "statusMessage": "No error."
        },
        "startTimestamp": 1668431165,
        "originalParentPID": 1
      },
      "matchType": "signingID",
      "timestamp": 1668431168.6704922,
      "matchValue": "com.ibm.cio.notifier"
    },
    "facts": [
      {
        "name": "PreventedExecution",
        "tags": [
          "PreventedExecution"
        ],
        "uuid": "76d06949-2f35-47b6-96be-05abe638790d",
        "human": "A process has been denied execution.",
        "actions": [
          {
            "name": "Report",
            "parameters": {}
          },
          {
            "name": "Prevented",
            "parameters": {}
          },
          {
            "name": "DisplayMessage",
            "parameters": {
              "title": "IBM Notifier Has Been Blocked.",
              "message": "This software is restricted by your organization. It has been blocked, moved to quarantine, and reported to your IT Administrator or Security Team."
            }
          }
        ],
        "context": [],
        "version": 0,
        "severity": 1
      }
    ],
    "custom": false,
    "actions": [
      {
        "name": "Report",
        "parameters": {}
      },
      {
        "name": "Prevented",
        "parameters": {}
      },
      {
        "name": "DisplayMessage",
        "parameters": {
          "title": "IBM Notifier Has Been Blocked.",
          "message": "This software is restricted by your organization. It has been blocked, moved to quarantine, and reported to your IT Administrator or Security Team."
        }
      }
    ],
    "context": [],
    "severity": 1
  },
  "related": {
    "files": [],
    "users": [
      {
        "uid": 501,
        "name": "thijs",
        "uuid": "Z2C23RW4DY1f5"
      }
    ],
    "groups": [
      {
        "gid": 20,
        "name": "staff",
        "uuid": "Z2C23RW4DY14"
      }
    ],
    "binaries": [
      {
        "gid": 20,
        "uid": 501,
        "fsid": 16777222,
        "mode": 33261,
        "path": "/Applications/IBM Notifier.app/Contents/MacOS/IBM Notifier",
        "size": 2617808,
        "inode": 2797471,
        "changed": 1668431168,
        "created": 1664772282,
        "sha1hex": "",
        "accessed": 1668431165,
        "modified": 1664772282,
        "sha256hex": "",
        "isDownload": false,
        "isAppBundle": false,
        "isDirectory": false,
        "signingInfo": {
          "appid": "com.ibm.cio.notifier",
          "cdhash": "XZClQWlwUsWw1uZnLhCOvyp7R0s=",
          "status": -67068,
          "teamid": "PETKK2G752",
          "signerType": 4,
          "authorities": [],
          "entitlements": [],
          "statusMessage": "cannot find code object on disk"
        },
        "isScreenShot": false
      }
    ],
    "processes": [
      {
        "gid": 20,
        "pid": 40990,
        "uid": 501,
        "args": [
          "/Applications/IBM Notifier.app/Contents/MacOS/IBM Notifier"
        ],
        "name": "IBM Notifier",
        "path": "/Applications/IBM Notifier.app/Contents/MacOS/IBM Notifier",
        "pgid": 40990,
        "ppid": 1,
        "rgid": 20,
        "ruid": 501,
        "uuid": "d073d34c-4282-46bd-b45b-7bb62e7d0f3d",
        "signingInfo": {
          "appid": "com.ibm.cio.notifier",
          "cdhash": "XZClQWlwUsWw1uZnLhCOvyp7R0s=",
          "status": 0,
          "teamid": "PETKK2G752",
          "signerType": 2,
          "authorities": [
            "Developer ID Application: International  Business Machines Corp (PETKK2G752)",
            "Developer ID Certification Authority",
            "Apple Root CA"
          ],
          "entitlements": [],
          "statusMessage": "No error."
        },
        "startTimestamp": 1668431165,
        "originalParentPID": 1
      }
    ]
  },
  "eventType": "GPPreventedExecutionEvent"
}

=== SkylerGodfrey/jamfprotect/json_samples_and_schemas/alerts/samples/GPThreatMatchExecEvent.json
{
  "host": {
    "os": "Version 14.0 (Build 23A344)",
    "ips": [
      "192.168.11.151"
    ],
    "serial": "C02ZW0GTLVDL",
    "hostname": "LMAC-ZW0GTLVDL",
    "protectVersion": "5.0.0.1",
    "provisioningUDID": "32EC79C5-26DC-535A-85F7-986F063297E2"
  },
  "match": {
    "tags": [],
    "uuid": "816d8012-dec5-4569-bf7a-04df2594ac42",
    "event": {
      "uuid": "19e11623-95ce-436e-9158-2002c643bbc3",
      "blocked": true,
      "process": {
        "gid": 0,
        "pid": 39356,
        "uid": 0,
        "args": [
          "/Library/JMTTrader/CrashReporter",
          "Maintain"
        ],
        "name": "CrashReporter",
        "path": "/Library/JMTTrader/CrashReporter",
        "pgid": 39356,
        "ppid": 1,
        "rgid": 0,
        "ruid": 0,
        "uuid": "3a842375-29f4-4516-8c8e-aca148c3ab32",
        "signingInfo": {
          "appid": "",
          "status": -67068,
          "teamid": "",
          "signerType": 4,
          "authorities": [],
          "entitlements": [],
          "statusMessage": "cannot find code object on disk"
        },
        "startTimestamp": 1668430737,
        "originalParentPID": 1
      },
      "matchType": "Threat Signature",
      "timestamp": 1668430737.24338,
      "matchValue": "applejeus_jmt_a"
    },
    "facts": [
      {
        "name": "ThreatMatchExecEvent",
        "tags": [
          "ThreatMatchExecEvent"
        ],
        "uuid": "3b434ba4-fd28-4c11-aeb9-ce571e81f712",
        "human": "A process has been denied execution.",
        "actions": [
          {
            "name": "DisplayMessage",
            "parameters": {
              "title": "CrashReporter Has Been Blocked.",
              "message": "This software has been identified as a malicious or potentially unwanted program. It has been blocked, moved to quarantine, and reported to your IT Administrator or Security Team."
            }
          },
          {
            "name": "Report",
            "parameters": {}
          },
          {
            "name": "Prevented",
            "parameters": {}
          }
        ],
        "context": [],
        "version": 11568,
        "severity": 3
      }
    ],
    "custom": false,
    "actions": [
      {
        "name": "DisplayMessage",
        "parameters": {
          "title": "CrashReporter Has Been Blocked.",
          "message": "This software has been identified as a malicious or potentially unwanted program. It has been blocked, moved to quarantine, and reported to your IT Administrator or Security Team."
        }
      },
      {
        "name": "Report",
        "parameters": {}
      },
      {
        "name": "Prevented",
        "parameters": {}
      }
    ],
    "context": [],
    "severity": 3
  },
  "related": {
    "files": [],
    "users": [
      {
        "uid": 0,
        "name": "root",
        "uuid": "C02ZW0GTLVDL0"
      }
    ],
    "groups": [
      {
        "gid": 0,
        "name": "wheel",
        "uuid": "C02ZW0GTLVDL0"
      }
    ],
    "binaries": [],
    "processes": [
      {
        "gid": 0,
        "pid": 39356,
        "uid": 0,
        "args": [
          "/Library/JMTTrader/CrashReporter",
          "Maintain"
        ],
        "name": "CrashReporter",
        "path": "/Library/JMTTrader/CrashReporter",
        "pgid": 39356,
        "ppid": 1,
        "rgid": 0,
        "ruid": 0,
        "uuid": "3a842375-29f4-4516-8c8e-aca148c3ab32",
        "signingInfo": {
          "appid": "",
          "status": -67068,
          "teamid": "",
          "signerType": 4,
          "authorities": [],
          "entitlements": [],
          "statusMessage": "cannot find code object on disk"
        },
        "startTimestamp": 1668430737,
        "originalParentPID": 1
      }
    ]
  },
  "eventType": "GPThreatMatchExecEvent"
}
