=== SkylerGodfrey/jamfprotect/json_samples_and_schemas/alerts/schemas/GPUSBEvent.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "host": {
      "type": "object",
      "properties": {
        "os": {
          "type": "string"
        },
        "ips": {
          "type": "array",
          "items": [
            {
              "type": "string"
            }
          ]
        },
        "serial": {
          "type": "string"
        },
        "hostname": {
          "type": "string"
        },
        "protectVersion": {
          "type": "string"
        },
        "provisioningUDID": {
          "type": "string"
        }
      },
      "required": [
        "os",
        "ips",
        "serial",
        "hostname",
        "protectVersion",
        "provisioningUDID"
      ]
    },
    "match": {
      "type": "object",
      "properties": {
        "tags": {
          "type": "array",
          "items": [
            {
              "type": "string"
            }
          ]
        },
        "uuid": {
          "type": "string"
        },
        "event": {
          "type": "object",
          "properties": {
            "type": {
              "type": "integer"
            },
            "uuid": {
              "type": "string"
            },
            "device": {
              "type": "object",
              "properties": {
                "size": {
                  "type": "integer"
                },
                "unit": {
                  "type": "integer"
                },
                "isLeaf": {
                  "type": "boolean"
                },
                "bsdName": {
                  "type": "string"
                },
                "bsdUnit": {
                  "type": "integer"
                },
                "busName": {
                  "type": "string"
                },
                "busPath": {
                  "type": "string"
                },
                "content": {
                  "type": "string"
                },
                "isWhole": {
                  "type": "boolean"
                },
                "bsdMajor": {
                  "type": "integer"
                },
                "bsdMinor": {
                  "type": "integer"
                },
                "protocol": {
                  "type": "string"
                },
                "revision": {
                  "type": "string"
                },
                "vendorId": {
                  "type": "string"
                },
                "blockSize": {
                  "type": "integer"
                },
                "mediaKind": {
                  "type": "string"
                },
                "mediaName": {
                  "type": "string"
                },
                "mediaPath": {
                  "type": "string"
                },
                "productId": {
                  "type": "string"
                },
                "devicePath": {
                  "type": "string"
                },
                "isInternal": {
                  "type": "boolean"
                },
                "isWritable": {
                  "type": "boolean"
                },
                "vendorName": {
                  "type": "string"
                },
                "deviceClass": {
                  "type": "integer"
                },
                "deviceModel": {
                  "type": "string"
                },
                "isEjectable": {
                  "type": "boolean"
                },
                "isEncrypted": {
                  "type": "boolean"
                },
                "isRemovable": {
                  "type": "boolean"
                },
                "productName": {
                  "type": "string"
                },
                "serialNumber": {
                  "type": "string"
                },
                "deviceSubClass": {
                  "type": "integer"
                },
                "isNetworkVolume": {
                  "type": "boolean"
                },
                "encryptionDetail": {
                  "type": "integer"
                }
              },
              "required": [
                "size",
                "unit",
                "isLeaf",
                "bsdName",
                "bsdUnit",
                "busName",
                "busPath",
                "content",
                "isWhole",
                "bsdMajor",
                "bsdMinor",
                "protocol",
                "revision",
                "vendorId",
                "blockSize",
                "mediaKind",
                "mediaName",
                "mediaPath",
                "productId",
                "devicePath",
                "isInternal",
                "isWritable",
                "vendorName",
                "deviceClass",
                "deviceModel",
                "isEjectable",
                "isEncrypted",
                "isRemovable",
                "productName",
                "serialNumber",
                "deviceSubClass",
                "isNetworkVolume",
                "encryptionDetail"
              ]
            },
            "timestamp": {
              "type": "number"
            },
            "usbAddress": {
              "type": "integer"
            }
          },
          "required": [
            "type",
            "uuid",
            "device",
            "timestamp",
            "usbAddress"
          ]
        },
        "facts": {
          "type": "array",
          "items": [
            {
              "type": "object",
              "properties": {
                "name": {
                  "type": "string"
                },
                "tags": {
                  "type": "array",
                  "items": [
                    {
                      "type": "string"
                    }
                  ]
                },
                "uuid": {
                  "type": "string"
                },
                "human": {
                  "type": "string"
                },
                "actions": {
                  "type": "array",
                  "items": [
                    {
                      "type": "object",
                      "properties": {
                        "name": {
                          "type": "string"
                        }
                      },
                      "required": [
                        "name"
                      ]
                    }
                  ]
                },
                "context": {
                  "type": "array",
                  "items": {}
                },
                "version": {
                  "type": "integer"
                },
                "severity": {
                  "type": "integer"
                }
              },
              "required": [
                "name",
                "tags",
                "uuid",
                "human",
                "actions",
                "context",
                "version",
                "severity"
              ]
            }
          ]
        },
        "custom": {
          "type": "boolean"
        },
        "actions": {
          "type": "array",
          "items": [
            {
              "type": "object",
              "properties": {
                "name": {
                  "type": "string"
                }
              },
              "required": [
                "name"
              ]
            }
          ]
        },
        "context": {
          "type": "array",
          "items": {}
        },
        "severity": {
          "type": "integer"
        }
      },
      "required": [
        "tags",
        "uuid",
        "event",
        "facts",
        "custom",
        "actions",
        "context",
        "severity"
      ]
    },
    "related": {
      "type": "object",
      "properties": {
        "files": {
          "type": "array",
          "items": {}
        },
        "users": {
          "type": "array",
          "items": {}
        },
        "groups": {
          "type": "array",
          "items": {}
        },
        "binaries": {
          "type": "array",
          "items": {}
        },
        "processes": {
          "type": "array",
          "items": {}
        }
      },
      "required": [
        "files",
        "users",
        "groups",
        "binaries",
        "processes"
      ]
    },
    "eventType": {
      "type": "string"
    }
  },
  "required": [
    "host",
    "match",
    "related",
    "eventType"
  ]
}

=== SkylerGodfrey/jamfprotect/json_samples_and_schemas/alerts/samples/GPUSBEvent.json
{
  "host": {
    "os": "Version 14.0 (Build 23A344)",
    "ips": [
      "192.168.11.151"
    ],
    "serial": "Z2C23RW4DY",
    "hostname": "VMAC-2C23RW4DY",
    "protectVersion": "5.0.0.1",
    "provisioningUDID": "32EC79C5-26DC-535A-85F7-986F063297E2"
  },
  "match": {
    "tags": [
      "Visibility"
    ],
    "uuid": "361cb6fb-a8be-43a9-8a06-6a7ae482e47b",
    "event": {
      "type": 0,
      "uuid": "cdcafcd3-c8c3-4a8c-89b8-366606d1c966",
      "device": {
        "size": 15376000000,
        "unit": 1,
        "isLeaf": false,
        "bsdName": "disk2",
        "bsdUnit": 2,
        "busName": "XHC2",
        "busPath": "IODeviceTree:/PCI0@0/RP05@1C,4/UPSB@0/DSB2@2/XHC2@0",
        "content": "GUID_partition_scheme",
        "isWhole": true,
        "bsdMajor": 1,
        "bsdMinor": 11,
        "protocol": "USB",
        "revision": "1.00",
        "vendorId": "0x0781",
        "blockSize": 512,
        "mediaKind": "IOMedia",
        "mediaName": "SanDisk Ultra USB 3.0 Media",
        "mediaPath": "IODeviceTree:/PCI0@0/RP05@1C,4/UPSB@0/DSB2@2/XHC2@0/@1:0",
        "productId": "0x5595",
        "devicePath": "IOService:/AppleACPIPlatformExpert/PCI0@0/AppleACPIPCI/RP05@1C,4/IOPP/UPSB@0/IOPP/DSB2@2/IOPP/XHC2@0/XHC2@00000000/SSP1@00100000/Ultra USB 3.0@00100000/IOUSBHostInterface@0/IOUSBMassStorageInterfaceNub/IOUSBMassStorageDriverNub/IOUSBMassStorageDriver/IOSCSILogicalUnitNub@0/IOSCSIPeripheralDeviceType00/IOBlockStorageServices",
        "isInternal": false,
        "isWritable": true,
        "vendorName": "SanDisk",
        "deviceClass": 0,
        "deviceModel": "Ultra USB 3.0",
        "isEjectable": true,
        "isEncrypted": false,
        "isMountable": false,
        "isRemovable": true,
        "productName": "Ultra USB 3.0",
        "serialNumber": "4C531001410227100573",
        "deviceSubClass": 0,
        "isNetworkVolume": false,
        "encryptionDetail": 0
      },
      "timestamp": 1695719606.718678,
      "usbAddress": 1
    },
    "facts": [
      {
        "name": "USBInserted",
        "tags": [
          "Visibility"
        ],
        "uuid": "b4fe77b3-f8d3-483d-ba29-ea2e1a5c44ea",
        "human": "USB device inserted",
        "actions": [
          {
            "name": "Report",
            "parameters": {}
          }
        ],
        "context": [],
        "version": 1,
        "severity": 0
      }
    ],
    "custom": false,
    "actions": [
      {
        "name": "Report",
        "parameters": {}
      }
    ],
    "context": [],
    "severity": 0
  },
  "related": {
    "files": [],
    "users": [],
    "groups": [],
    "binaries": [],
    "processes": []
  },
  "eventType": "GPUSBEvent"
}
